### ISSUE TITLE
OpenAPI 3.0 detector code too strict during version checking

### ISSUE THREAD

**Issue by DanaEpp** [hahwul/noir#25]
Your recent commit for #15 definitely supports OAS3, but may be too stringent. 

Supporting OAS3, should, at a very minimum, also support minor updates (ie: v3.0.1, v3.0.2 etc). In fact, the regex should really support all 3.0.x. OpenAPI is already publishing 3.1, so you might want to consider even including the major updates too; very little will change for URL path extraction from the JSON/YML.

As of right now, noir can't really detect any up-to-date OAS spec file.   

As a test, I tried to force a downgrade of the version to 3.0.0 for OWASP's [crAPI spec doc](https://github.com/OWASP/crAPI/blob/develop/openapi-spec/openapi-spec.json). An updated analysis with noir will throw the following exception:

![image](https://github.com/hahwul/noir/assets/11337016/d72d99a9-8eff-4f02-82bf-a55fcaff6ca7)

Love the work you are doing. Has a lot of potential. For finding the attack surface of APIs accounting for more than the base OAS3 would be very beneficial. It might require some tweaking on the detector and analyzer.

HTH.

**Comment by hahwul** [comment]
Hi @DanaEpp 
First, Thank you for your feedback! I appreciate it. I was debating whether to check the version accurately or to check it flexibly, like using "3.0.x", but your suggestion today has made it clear for me. I'll explore developing in a way that handles multiple versions simultaneously.

The part you sent in the screenshot seems to be a bug. I'll check it out right away!

**Comment by hahwul** [comment]
I released the updated version include this patch, and I'll go ahead and close this issue for now. If it happens to resurface, please feel free to reopen it!
