### ISSUE TITLE
Consider adding a GitHub action to publish to homebrew when merging into main (or release) branch

### ISSUE THREAD

**Issue by DanaEpp** [hahwul/noir#26]
I'm a big fan of keeping brew releases up to date with Github releases. Your recent changes to add OAS3 support as part of issue #15 is NOT properly reflected in the current v0.4.0 release. 

An enhancement suggestion would be to consider automating your CICD pipeline with a GitHub action to push to homebrew when merging into the main branch. [Articles like this one](https://extrawurst.medium.com/github-actions-homebrew-%EF%B8%8F-2789ae5023fd), or [marketplace actions like this one](https://github.com/marketplace/actions/homebrew-releaser) might go a long way to helping keep what is in brew in sync with what is actually in GitHub. 

Just a suggestion. But I'd rather use homebrew to manage noir than have to pull and build when the versioning isn't already matching up.

HTH.

**Comment by DanaEpp** [comment]
This might be a decent add-on request to #19. If you are building static bins you may as well also push to your brew tap.

**Comment by hahwul** [comment]
@DanaEpp 
Thank you so much for the great suggestion! Personally, I've been on the lookout for a tool to assist with releasing Crystal apps, something akin to GoReleaser for Golang, but it seems there isn't an ideal solution available 😭

At the moment, considering the current situation, I believe the GitHub Action you mentioned is the best alternative. I'll give it a try soon!

Oh, by the way, as you mentioned, the OAS3 part was developed after the release of version 0.4, so for those using Homebrew, it might not have the latest source code.

**Comment by hahwul** [comment]
I added [GitHub Actions](https://github.com/hahwul/noir/actions/workflows/homebrew_publish.yml) to automate the Homebrew tap publishing process. It seems to have worked well in the recent release. There are separate things to consider about #19, so I'll close this issue for now. Thanks again for your support!

## Detail
Action worked successfully
![](https://github.com/hahwul/noir/assets/13212227/fabd2ab0-c047-42d7-a1ac-bdbbd3abe84f)

Homebrew tap is also automatically pushed and works fine
![](https://github.com/hahwul/noir/assets/13212227/b3a7e55f-342f-452b-850f-c82ab69eab53)
