### ISSUE TITLE
Support C#

### ISSUE THREAD

**Issue by infosec-au** [hahwul/noir#61]
Hey, I love this tool. It would be great if it supported C#.

C# routes are often defined in the MVC construct. https://www.tutorialsteacher.com/mvc/routing-in-mvc

MVC routes would probably be the easiest pattern to identify and report on.

Additionally, routes can also be defined as web services exposed via ASMX or SVC files, or inside the web.config file.

.NET has the concept of HTTPModules which are triggered on every request, and also has the concept of IS API DLL extensions, which are typically executed when hitting the specific DLL file in the web root. All of these could be great to detect and easy to as well from reading the web.config file.

**Comment by hahwul** [comment]
Hi @infosec-au 
Thank you so much for your opinion! 
I'll actively work on developing the aspects you mentioned to make them supported!

**Comment by hahwul** [comment]
I started with MVC first. Since I'm not very familiar with C#, I can currently only identify URLs. I'll need to gradually improve from here.
