### ISSUE TITLE
Improve Multi-Tech Analysis within a Single Directory (SpeedUp and More accurate detection)

### ISSUE THREAD

**Issue by hahwul** [hahwul/noir#80]
I believe this issue can be resolved with the following code. 

```ruby
# Code1
locator = CodeLocator.instance
locator.set("rails-home", dirname)
```

```ruby
# Code2
puts locator.get("rails-home")
```

Therefore, it would be beneficial to utilize a singleton key-value pair in the format of `techname-home` for each technology.

**Comment by hahwul** [comment]
## Diff
```bash
# Old (438 endpoints found -> Finally identified 47 endpoints.)
noir -b ./spec/functional_test/fixtures/

# New (88 endpoints found -> Finally identified 81 endpoints.)
./bin/noir -b ./spec/functional_test/fixtures/
```

**Comment by ksg97031** [comment]
보편적이진 않지만 한가지 우려되는 점이, 프로젝트 내부에 여러 모듈(A, B, C)을 분리해서 넣어놓는 경우가 있습니다.
`build.gradle, ModuleA/build.gradle, ModuleB/build.gradle, ModuleC/build.gradle`

상위 경로(root)에서 Detect되는 경우 하위 디렉터리까지 어차피 보기 때문에 문제가 없지만,
<img width="279" alt="image" src="https://github.com/hahwul/noir/assets/6715194/263e148a-610c-440c-b144-73933102f10b">

상위 경로가 아닌 모듈 단위로 Detect가 필요한 경우는 뒤에 모듈은 스캔이 누락될 수도 있을 것 같습니다.
<img width="279" alt="image" src="https://github.com/hahwul/noir/assets/6715194/5838a39a-8e4a-484e-8098-db146136a63c">

또 다른 문제는 빌드 명령어 없이는 의존관계를 정확히 따지기가 어려워서 누락이 발생할 수도 있습니다.
<img width="302" alt="image" src="https://github.com/hahwul/noir/assets/6715194/c5a9b3b6-096b-4acb-9b63-ca8b4fde6854">

제 당장의 의견으로는 자바 프로젝트는 하위 모듈이 Detect되는 경우 무조건 build.gradle, pom.xml 파일 여부를 토대로 상위 경로를 base_path로 정하는 것이 어떨까 싶고요! 
<img width="302" alt="image" src="https://github.com/hahwul/noir/assets/6715194/ab30c646-3400-4232-8779-d6e4f1af3285">

다른 하나는 Detector 동작에서 하나가 아닌 복수개의 base_path를 가질 필요가 있는지도 고민해보면 좋을 것 같습니다~

**Comment by hahwul** [comment]
@ksg97031 
좋은 의견 감사합니다! 이야기 나누면서 생각해보니 한 디렉토리 내 동일한 Tech의 여러 앱이 있는 경우도 문제가 되겠네요.
`--multiapps` 같은 flag로 on 하는 경우에만 동작시킬까 하다가 디렉토리 내 여러 앱이 있는 경우가 흔치 않고, 있다고 하더라도 URL이 다를 가능성도 높아서.. 득보다 실이 더 커보이는 느낌이네요. 

이 기능은 원복하고, 추후에 꼭 필요한 기능이라고 판단되면 그때 다시 고민해서 적용해보는게 좋을 것 같습니다!
(사실 중첩 앱인 경우에 오히려 여러 base_path가 중복으로 스캔해야할 수도 있어서 비효율적으로 보였습니다)

그럼 즐거운 하루 보내세요 :D
