### ISSUE TITLE
Support Django

### ISSUE THREAD

**Issue by ksg97031** [hahwul/noir#9]
@hahwul 
생각나서 저도 코드를 작성해봤습니다~ (코드는 개판인 것 같긴해요 ㅠ)
https://github.com/ksg97031/noir/tree/support-django

---
ROOT_URLCONF 글로벌 변수를 읽어서 기준이되는 urls.py를 가져옵니다. (search_root_django_urls_list)
가져온 파일에서 추가로 포함시키는 urls.py를 추가로 검색합니다. (include() 형태만 가능)
검색 시 상위 URL Prefix를 계속 전달시키는 방법으로 최종 URL 엔드포인트를 만들었습니다.

View 파일을 가져오는 것도 작성했는데, 생각보다 코드를 봐도 GET, POST를 바로 알 수 있지 않아서 이건 좀 더 확인이 필요해보입니다.
아마 기본이 GET 이거나, 함수명에 따라 메소드가 정해지는 것 같아서 가능한 것만 추가하면 될 듯합니다~

아래 두 프로젝트로 테스트했는데 결과가 나쁘지 않은 것 같아 공유드립니다~
https://github.com/django/djangoproject.com
https://github.com/liangliangyy/DjangoBlog

**Comment by hahwul** [comment]
@ksg97031 
앞으로 detector와 analyzer 가 test code를 기반으로 기능의 커버리지와 성능을 측정하고 개선해 나갈 예정이에요.
(현재 그나마 제일 유사한 구조는 spring)

Django 부분 정리되면 코드 머지 후 analyzer 모델의 analyze 함수와 같이 line->endpoint(url,param,etc...) 등을 추출하는 형태의 공통 함수를 만들고 이를 통해서 여러 코드 패턴을 체크해 볼 생각입니다. (spring 쪽에 적용된 부분이 여러 케이스를 체크할 수 있어서 좋았네요.)

https://github.com/hahwul/noir/blob/2872a9d33d3cb231048f81b726db2d5533995c4b/src/models/analyzer.cr#L26

혹시나 해서 방향성은 공유해 드리니 참고 부탁드립니다 :D
