### ISSUE TITLE
OAS3 Detected- Missing hash key: "servers" (KeyError)

### ISSUE THREAD

**Issue by ephiot** [hahwul/noir#90]
I'm running Noir against a Typescript project, I know that it currently not support Typescript and noted the it ignores and no problem, but it detects OAS3, and throws an Unhandled Exception:
```
              .__
  ____   ____ |__|______
/    \ /  _ \|  \_  __ \
|   |  (  <♠> )  ||  | \/
|___|  /\____/|__||__|
     \/                 v0.7.0

 

[*] Detecting technologies to base directory.
[I] Detected 1 technologies.
    oas3
[*] Initiate code analysis based on the detected technology.
[*] Starting analysis of endpoints.
    17 Analyzers initialized
    Analysis to 1 technologies
Unhandled exception: Missing hash key: "servers" (KeyError)
  from noir in '??'
  from noir in '??'
  from noir in '??'
  from noir in '__crystal_main'
  from noir in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from noir in '_start'
  from ???
```
I`m using Kali Linux 2023.1 (kali-roolling), this behavior is expected ?

**Comment by hahwul** [comment]
Hi @ephiot 
Thank you so much for the report! I'm currently working on fixing this issue and preparing the release for version 7.0.1. Once the release is complete, I'd appreciate it if you could test it out for me. :D

**Comment by hahwul** [comment]
@ephiot 
The release has just been [completed](https://github.com/hahwul/noir/releases/tag/v0.7.1). I didn't have any problems when testing, but if it reoccurs in your case, please re-open the issue! Then have a nice day.

![](https://github.com/hahwul/noir/assets/13212227/10b7c494-4b66-47f3-a010-e15ed14ac115)
